// SoundTune/Views/DesignSystem/Localization.swift
import Foundation
import Observation

enum AppLanguage: String, Codable, CaseIterable, Identifiable {
    case system
    case english = "en"
    case turkish = "tr"
    case german = "de"
    case spanish = "es"
    case french = "fr"
    
    var id: String { rawValue }
    
    var displayName: String {
        switch self {
        case .system: return "System"
        case .english: return "English"
        case .turkish: return "Türkçe"
        case .german: return "Deutsch"
        case .spanish: return "Español"
        case .french: return "Français"
        }
    }

    var resolvedLanguage: AppLanguage {
        guard self == .system else { return self }
        return Self.resolve(preferredLanguages: Locale.preferredLanguages)
    }

    var locale: Locale {
        switch resolvedLanguage {
        case .turkish:
            return Locale(identifier: "tr_TR")
        case .german:
            return Locale(identifier: "de_DE")
        case .spanish:
            return Locale(identifier: "es_ES")
        case .french:
            return Locale(identifier: "fr_FR")
        case .system, .english:
            return Locale(identifier: "en_US")
        }
    }

    static func resolve(languageCode: String?) -> AppLanguage {
        supportedLanguage(for: languageCode) ?? .english
    }

    static func resolve(preferredLanguages: [String]) -> AppLanguage {
        for identifier in preferredLanguages {
            if let language = supportedLanguage(for: normalizedLanguageCode(from: identifier)) {
                return language
            }
        }
        return .english
    }

    private static func supportedLanguage(for languageCode: String?) -> AppLanguage? {
        guard let languageCode = normalizedLanguageCode(from: languageCode) else { return nil }
        return allCases.first { language in
            language != .system && language.rawValue == languageCode
        }
    }

    private static func normalizedLanguageCode(from identifier: String?) -> String? {
        guard let identifier, !identifier.isEmpty else { return nil }
        return identifier.replacingOccurrences(of: "_", with: "-")
            .split(separator: "-")
            .first
            .map { String($0).lowercased() }
    }
}

@Observable
@MainActor
final class LanguageManager {
    static let shared = LanguageManager()
    
    var currentLanguage: AppLanguage = .system
    
    private var translations: [String: [String: String]] = [:]

    private let supplementalTranslations: [String: [String: String]] = [
        "Launch at Login": ["de": "Beim Anmelden starten", "es": "Abrir al iniciar sesión", "fr": "Lancer à l’ouverture de session"],
        "Start SoundTune when you log in": ["de": "SoundTune beim Anmelden starten", "es": "Inicia SoundTune al iniciar sesión", "fr": "Lance SoundTune à l’ouverture de session"],
        "Theme": ["de": "Erscheinungsbild", "es": "Tema", "fr": "Thème"],
        "Match macOS, or lock to Light or Dark": ["de": "macOS folgen oder Hell/Dunkel festlegen", "es": "Sigue macOS o fija claro u oscuro", "fr": "Suivre macOS ou forcer clair ou sombre"],
        "Volume": ["de": "Lautstärke", "es": "Volumen", "fr": "Volume"],
        "Default Volume": ["de": "Standardlautstärke", "es": "Volumen predeterminado", "fr": "Volume par défaut"],
        "Initial volume for new apps": ["de": "Anfangslautstärke für neue Apps", "es": "Volumen inicial para apps nuevas", "fr": "Volume initial pour les nouvelles apps"],
        "Loudness Compensation": ["de": "Loudness-Kompensation", "es": "Compensación de sonoridad", "fr": "Compensation de loudness"],
        "Boost low frequencies at low volume": ["de": "Tiefe Frequenzen bei niedriger Lautstärke anheben", "es": "Refuerza graves a bajo volumen", "fr": "Renforce les graves à faible volume"],
        "Devices": ["de": "Geräte", "es": "Dispositivos", "fr": "Appareils"],
        "Lock Input Device": ["de": "Eingabegerät sperren", "es": "Bloquear dispositivo de entrada", "fr": "Verrouiller l’appareil d’entrée"],
        "Prevent auto-switching when devices connect": ["de": "Automatisches Umschalten beim Verbinden verhindern", "es": "Evita cambios automáticos al conectar dispositivos", "fr": "Empêche le changement automatique à la connexion"],
        "System Sounds": ["de": "Systemtöne", "es": "Sonidos del sistema", "fr": "Sons système"],
        "Where alerts and effects play": ["de": "Wo Warnungen und Effekte abgespielt werden", "es": "Dónde se reproducen alertas y efectos", "fr": "Où jouent les alertes et les effets"],
        "Alert Volume": ["de": "Hinweislautstärke", "es": "Volumen de alertas", "fr": "Volume des alertes"],
        "Volume for alerts and notifications": ["de": "Lautstärke für Hinweise und Mitteilungen", "es": "Volumen para alertas y notificaciones", "fr": "Volume des alertes et notifications"],
        "Language": ["de": "Sprache", "es": "Idioma", "fr": "Langue"],
        "App Language": ["de": "App-Sprache", "es": "Idioma de la app", "fr": "Langue de l’app"],
        "Follow macOS or choose a language": ["de": "macOS folgen oder eine Sprache wählen", "es": "Sigue macOS o elige un idioma", "fr": "Suivre macOS ou choisir une langue"],
        "Quit": ["de": "Beenden", "es": "Salir", "fr": "Quitter"],
        "Quit SoundTune": ["de": "SoundTune beenden", "es": "Salir de SoundTune", "fr": "Quitter SoundTune"],
        "Output Devices": ["de": "Ausgabegeräte", "es": "Dispositivos de salida", "fr": "Appareils de sortie"],
        "Input Devices": ["de": "Eingabegeräte", "es": "Dispositivos de entrada", "fr": "Appareils d’entrée"],
        "Apps": ["de": "Apps", "es": "Apps", "fr": "Apps"],
        "No apps playing audio": ["de": "Keine Apps spielen Audio", "es": "No hay apps reproduciendo audio", "fr": "Aucune app ne lit de l’audio"],
        "ignored · edit to manage": ["de": "ignoriert · zum Verwalten bearbeiten", "es": "ignorada · edita para gestionar", "fr": "ignorée · modifier pour gérer"],
        "ignored": ["de": "ignoriert", "es": "ignorada", "fr": "ignorée"],
        "Ignored": ["de": "Ignoriert", "es": "Ignoradas", "fr": "Ignorées"],
        "Turn on Bluetooth to connect devices": ["de": "Bluetooth einschalten, um Geräte zu verbinden", "es": "Activa Bluetooth para conectar dispositivos", "fr": "Activez Bluetooth pour connecter des appareils"],
        "Paired": ["de": "Gekoppelt", "es": "Emparejados", "fr": "Appairés"],
        "Connecting...": ["de": "Verbinden...", "es": "Conectando...", "fr": "Connexion..."],
        "Disconnecting...": ["de": "Trennen...", "es": "Desconectando...", "fr": "Déconnexion..."],
        "Connected": ["de": "Verbunden", "es": "Conectado", "fr": "Connecté"],
        "Bluetooth is off": ["de": "Bluetooth ist aus", "es": "Bluetooth está desactivado", "fr": "Le Bluetooth est désactivé"],
        "AirPods Settings": ["de": "AirPods-Einstellungen", "es": "Ajustes de AirPods", "fr": "Réglages des AirPods"],
        "Not Available": ["de": "Nicht verfügbar", "es": "No disponible", "fr": "Non disponible"],
        "Open AirPods Settings": ["de": "AirPods-Einstellungen öffnen", "es": "Abrir ajustes de AirPods", "fr": "Ouvrir les réglages AirPods"],
        "Open Headphone Settings": ["de": "Kopfhörer-Einstellungen öffnen", "es": "Abrir ajustes de auriculares", "fr": "Ouvrir les réglages du casque"],
        "Settings": ["de": "Einstellungen", "es": "Ajustes", "fr": "Réglages"],
        "Done reordering": ["de": "Sortierung fertig", "es": "Reordenación finalizada", "fr": "Réorganisation terminée"],
        "Reorder devices": ["de": "Geräte sortieren", "es": "Reordenar dispositivos", "fr": "Réorganiser les appareils"],
        "Drag or type a number to set priority": ["de": "Ziehen oder eine Zahl eingeben, um die Priorität festzulegen", "es": "Arrastra o escribe un número para definir la prioridad", "fr": "Faites glisser ou saisissez un numéro pour définir la priorité"],
        "No Output": ["de": "Keine Ausgabe", "es": "Sin salida", "fr": "Aucune sortie"],
        "No Input": ["de": "Keine Eingabe", "es": "Sin entrada", "fr": "Aucune entrée"],
        "Open System Settings": ["de": "Systemeinstellungen öffnen", "es": "Abrir Ajustes del Sistema", "fr": "Ouvrir Réglages Système"],
        "Grant Access": ["de": "Zugriff erlauben", "es": "Conceder acceso", "fr": "Autoriser l’accès"],
        "Use SoundTune's software volume": ["de": "Software-Lautstärke von SoundTune verwenden", "es": "Usar el volumen por software de SoundTune", "fr": "Utiliser le volume logiciel de SoundTune"],
        "Transport": ["de": "Verbindung", "es": "Transporte", "fr": "Connexion"],
        "Sample rate": ["de": "Abtastrate", "es": "Frecuencia de muestreo", "fr": "Fréquence d’échantillonnage"],
        "Format": ["de": "Format", "es": "Formato", "fr": "Format"],
        "Device ID": ["de": "Geräte-ID", "es": "ID del dispositivo", "fr": "ID de l’appareil"],
        "Copy device ID": ["de": "Geräte-ID kopieren", "es": "Copiar ID del dispositivo", "fr": "Copier l’ID de l’appareil"],
        "Copied": ["de": "Kopiert", "es": "Copiado", "fr": "Copié"],
        "Device ID copied": ["de": "Geräte-ID kopiert", "es": "ID del dispositivo copiado", "fr": "ID de l’appareil copiée"],
        "General": ["de": "Allgemein", "es": "General", "fr": "Général"],
        "Muted": ["de": "Stumm", "es": "Silenciado", "fr": "Muet"],
        "General Settings": ["de": "Allgemeine Einstellungen", "es": "Ajustes generales", "fr": "Réglages généraux"],
        "SoundTune Settings": ["de": "SoundTune-Einstellungen", "es": "Ajustes de SoundTune", "fr": "Réglages de SoundTune"],
        "System": ["de": "System", "es": "Sistema", "fr": "Système"],
        "Light": ["de": "Hell", "es": "Claro", "fr": "Clair"],
        "Dark": ["de": "Dunkel", "es": "Oscuro", "fr": "Sombre"],
        "Hardware": ["de": "Hardware", "es": "Hardware", "fr": "Matériel"],
        "Software": ["de": "Software", "es": "Software", "fr": "Logiciel"],
        "Follow system default": ["de": "Systemstandard folgen", "es": "Seguir predeterminado del sistema", "fr": "Suivre le réglage par défaut du système"],
        "Follows default": ["de": "Folgt Standard", "es": "Sigue predeterminado", "fr": "Suit le réglage par défaut"],
        "Follows System Default": ["de": "Folgt Systemstandard", "es": "Sigue el predeterminado del sistema", "fr": "Suit le réglage système par défaut"],
        "Use system default": ["de": "Systemstandard verwenden", "es": "Usar predeterminado del sistema", "fr": "Utiliser le réglage système par défaut"],
        "Select output...": ["de": "Ausgabe wählen...", "es": "Seleccionar salida...", "fr": "Choisir une sortie..."],
        "Pin to menu": ["de": "Im Menü anheften", "es": "Fijar al menú", "fr": "Épingler au menu"],
        "Hide app": ["de": "App ausblenden", "es": "Ocultar app", "fr": "Masquer l’app"],
        "Reset all settings?": ["de": "Alle Einstellungen zurücksetzen?", "es": "¿Restablecer todos los ajustes?", "fr": "Réinitialiser tous les réglages ?"],
        "Reset": ["de": "Zurücksetzen", "es": "Restablecer", "fr": "Réinitialiser"],
        "Cancel": ["de": "Abbrechen", "es": "Cancelar", "fr": "Annuler"],
        "This cannot be undone.": ["de": "Dies kann nicht rückgängig gemacht werden.", "es": "Esto no se puede deshacer.", "fr": "Cette action est irréversible."],
        "Equalizer": ["de": "Equalizer", "es": "Ecualizador", "fr": "Égaliseur"],
        "Device EQ": ["de": "Geräte-EQ", "es": "EQ del dispositivo", "fr": "EQ de l’appareil"],
        "Bypass": ["de": "Umgehen", "es": "Omitir", "fr": "Contourner"],
        "Preamp": ["de": "Vorverstärkung", "es": "Preamplificador", "fr": "Préampli"],
        "Reset EQ": ["de": "EQ zurücksetzen", "es": "Restablecer EQ", "fr": "Réinitialiser l’EQ"],
        "Preset": ["de": "Preset", "es": "Preajuste", "fr": "Préréglage"],
        "Save preset...": ["de": "Preset speichern...", "es": "Guardar preajuste...", "fr": "Enregistrer le préréglage..."],
        "Flat": ["de": "Flach", "es": "Plano", "fr": "Plat"],
        "Default": ["de": "Standard", "es": "Predeterminado", "fr": "Par défaut"],
        "Active Device": ["de": "Aktives Gerät", "es": "Dispositivo activo", "fr": "Appareil actif"],
        "No devices found": ["de": "Keine Geräte gefunden", "es": "No se encontraron dispositivos", "fr": "Aucun appareil trouvé"],
        "Custom Preset": ["de": "Eigenes Preset", "es": "Preajuste personalizado", "fr": "Préréglage personnalisé"],
        "Delete preset": ["de": "Preset löschen", "es": "Eliminar preajuste", "fr": "Supprimer le préréglage"],
        "Save Preset": ["de": "Preset speichern", "es": "Guardar preajuste", "fr": "Enregistrer le préréglage"],
        "Preset Name": ["de": "Preset-Name", "es": "Nombre del preajuste", "fr": "Nom du préréglage"],
        "Save": ["de": "Speichern", "es": "Guardar", "fr": "Enregistrer"],
        "AutoEQ Profile": ["de": "AutoEQ-Profil", "es": "Perfil de AutoEQ", "fr": "Profil AutoEQ"],
        "Select a profile...": ["de": "Profil wählen...", "es": "Seleccionar perfil...", "fr": "Choisir un profil..."],
        "Search headphone models...": ["de": "Kopfhörermodelle suchen...", "es": "Buscar modelos de auriculares...", "fr": "Rechercher des modèles de casque..."],
        "Device Priority": ["de": "Gerätepriorität", "es": "Prioridad de dispositivos", "fr": "Priorité des appareils"],
        "Volume Boost": ["de": "Lautstärke-Boost", "es": "Aumento de volumen", "fr": "Amplification du volume"],
        "None": ["de": "Keine", "es": "Ninguno", "fr": "Aucun"],
        "Search autoEQ profiles...": ["de": "AutoEQ-Profile suchen...", "es": "Buscar perfiles AutoEQ...", "fr": "Rechercher des profils AutoEQ..."],
        "AutoEQ Enabled": ["de": "AutoEQ aktiviert", "es": "AutoEQ activado", "fr": "AutoEQ activé"],
        "AutoEQ Preamp": ["de": "AutoEQ-Vorverstärkung", "es": "Preamplificador AutoEQ", "fr": "Préampli AutoEQ"],
        "Add to Favorites": ["de": "Zu Favoriten hinzufügen", "es": "Añadir a favoritos", "fr": "Ajouter aux favoris"],
        "Remove from Favorites": ["de": "Aus Favoriten entfernen", "es": "Eliminar de favoritos", "fr": "Retirer des favoris"],
        "Search headphones...": ["de": "Kopfhörer suchen...", "es": "Buscar auriculares...", "fr": "Rechercher des casques..."],
        "Import AutoEQ Profile": ["de": "AutoEQ-Profil importieren", "es": "Importar perfil AutoEQ", "fr": "Importer un profil AutoEQ"],
        "Favorites": ["de": "Favoriten", "es": "Favoritos", "fr": "Favoris"],
        "Catalog": ["de": "Katalog", "es": "Catálogo", "fr": "Catalogue"],
        "Close": ["de": "Schließen", "es": "Cerrar", "fr": "Fermer"],
        "Custom": ["de": "Eigen", "es": "Personalizado", "fr": "Personnalisé"],
        "Open %@": ["de": "%@ öffnen", "es": "Abrir %@", "fr": "Ouvrir %@"],
        "Close Equalizer": ["de": "Equalizer schließen", "es": "Cerrar ecualizador", "fr": "Fermer l’égaliseur"],
        "Connect": ["de": "Verbinden", "es": "Conectar", "fr": "Connecter"],
        "Pin app": ["de": "App anheften", "es": "Fijar app", "fr": "Épingler l’app"],
        "Unpin app": ["de": "App lösen", "es": "Desfijar app", "fr": "Désépingler l’app"],
        "Ignore app": ["de": "App ignorieren", "es": "Ignorar app", "fr": "Ignorer l’app"],
        "Stop ignoring": ["de": "Nicht mehr ignorieren", "es": "Dejar de ignorar", "fr": "Ne plus ignorer"],
        "No correction active": ["de": "Keine Korrektur aktiv", "es": "No hay corrección activa", "fr": "Aucune correction active"],
        "Search or pick a favorite below": ["de": "Suchen oder unten einen Favoriten wählen", "es": "Busca o elige un favorito abajo", "fr": "Recherchez ou choisissez un favori ci-dessous"],
        "Loading profile...": ["de": "Profil wird geladen...", "es": "Cargando perfil...", "fr": "Chargement du profil..."],
        "Correction": ["de": "Korrektur", "es": "Corrección", "fr": "Correction"],
        "Clear search": ["de": "Suche löschen", "es": "Borrar búsqueda", "fr": "Effacer la recherche"],
        "Loading headphone catalog...": ["de": "Kopfhörerkatalog wird geladen...", "es": "Cargando catálogo de auriculares...", "fr": "Chargement du catalogue de casques..."],
        "Type to search headphones": ["de": "Tippen, um Kopfhörer zu suchen", "es": "Escribe para buscar auriculares", "fr": "Saisissez pour rechercher des casques"],
        "No profiles found": ["de": "Keine Profile gefunden", "es": "No se encontraron perfiles", "fr": "Aucun profil trouvé"],
        "Import ParametricEQ.txt...": ["de": "ParametricEQ.txt importieren...", "es": "Importar ParametricEQ.txt...", "fr": "Importer ParametricEQ.txt..."],
        "Showing %d of %d results": ["de": "%d von %d Ergebnissen", "es": "Mostrando %d de %d resultados", "fr": "%d résultats sur %d affichés"],
        "%d results": ["de": "%d Ergebnisse", "es": "%d resultados", "fr": "%d résultats"],
        "Single": ["de": "Einzeln", "es": "Único", "fr": "Unique"],
        "Multi": ["de": "Mehrfach", "es": "Múltiple", "fr": "Multiple"],
        "Select": ["de": "Auswählen", "es": "Seleccionar", "fr": "Sélectionner"],
        "Music": ["de": "Musik", "es": "Música", "fr": "Musique"],
        "Media": ["de": "Medien", "es": "Medios", "fr": "Média"],
        "Save current EQ as preset": ["de": "Aktuellen EQ als Preset speichern", "es": "Guardar EQ actual como preajuste", "fr": "Enregistrer l’EQ actuelle comme préréglage"],
        "Preset name": ["de": "Preset-Name", "es": "Nombre del preajuste", "fr": "Nom du préréglage"],
        "Rename preset": ["de": "Preset umbenennen", "es": "Renombrar preajuste", "fr": "Renommer le préréglage"],
        "Unmute": ["de": "Stummschaltung aufheben", "es": "Activar sonido", "fr": "Réactiver le son"],
        "Mute": ["de": "Stummschalten", "es": "Silenciar", "fr": "Couper le son"],
        "Check Now": ["de": "Jetzt prüfen", "es": "Comprobar ahora", "fr": "Vérifier maintenant"],
        "Volume Step": ["de": "Lautstärkeschritt", "es": "Paso de volumen", "fr": "Pas de volume"],
        "How much each keypress changes the volume": ["de": "Wie stark jeder Tastendruck die Lautstärke ändert", "es": "Cuánto cambia el volumen con cada pulsación", "fr": "Amplitude du changement de volume à chaque touche"],
        "Media Keys": ["de": "Medientasten", "es": "Teclas multimedia", "fr": "Touches multimédias"],
        "Media Keys Control": ["de": "Medientastensteuerung", "es": "Control de teclas multimedia", "fr": "Contrôle des touches multimédias"],
        "Use F11/F12 (or volume keys) to control SoundTune": ["de": "F11/F12 oder Lautstärketasten steuern SoundTune", "es": "Usa F11/F12 o las teclas de volumen para controlar SoundTune", "fr": "Utilisez F11/F12 ou les touches de volume pour contrôler SoundTune"],
        "HUD Style": ["de": "HUD-Stil", "es": "Estilo del HUD", "fr": "Style du HUD"],
        "How the volume indicator appears": ["de": "Darstellung der Lautstärkeanzeige", "es": "Cómo aparece el indicador de volumen", "fr": "Apparence de l’indicateur de volume"],
        "Hotkeys": ["de": "Tastenkürzel", "es": "Atajos", "fr": "Raccourcis"],
        "Show or hide the menu bar popup": ["de": "Menüleisten-Popup ein- oder ausblenden", "es": "Muestra u oculta el panel de la barra de menús", "fr": "Afficher ou masquer le panneau de la barre des menus"],
        "Open settings view": ["de": "Einstellungen öffnen", "es": "Abrir vista de ajustes", "fr": "Ouvrir les réglages"],
        "Raise volume for the app playing audio": ["de": "Lautstärke der aktiven Audio-App erhöhen", "es": "Sube el volumen de la app que reproduce audio", "fr": "Augmenter le volume de l’app qui lit l’audio"],
        "Lower volume for the app playing audio": ["de": "Lautstärke der aktiven Audio-App senken", "es": "Baja el volumen de la app que reproduce audio", "fr": "Baisser le volume de l’app qui lit l’audio"],
        "Mute or unmute the app playing audio": ["de": "Audio-App stummschalten oder Stummschaltung aufheben", "es": "Silencia o reactiva la app que reproduce audio", "fr": "Couper ou réactiver le son de l’app qui lit l’audio"],
        "Welcome to SoundTune": ["de": "Willkommen bei SoundTune", "es": "Bienvenido a SoundTune", "fr": "Bienvenue dans SoundTune"],
        "Equalizer & Presets": ["de": "Equalizer & Presets", "es": "Ecualizador y preajustes", "fr": "Égaliseur et préréglages"],
        "Fine-tune audio with per-app and per-device EQ presets.": ["de": "Feinabstimmung mit EQ-Presets pro App und Gerät.", "es": "Ajusta el audio con preajustes de EQ por app y dispositivo.", "fr": "Ajustez l’audio avec des préréglages d’EQ par app et appareil."],
        "Next": ["de": "Weiter", "es": "Siguiente", "fr": "Suivant"],
        "Get Started": ["de": "Loslegen", "es": "Empezar", "fr": "Commencer"],
        "Per-App Volume Control": ["de": "Lautstärke pro App", "es": "Volumen por app", "fr": "Volume par app"],
        "Set different volume levels for each app independently.": ["de": "Lege für jede App eigene Lautstärken fest.", "es": "Define niveles de volumen distintos para cada app.", "fr": "Définissez un volume différent pour chaque app."],
        "Required Permissions": ["de": "Erforderliche Berechtigungen", "es": "Permisos necesarios", "fr": "Autorisations requises"],
        "Accessibility": ["de": "Bedienungshilfen", "es": "Accesibilidad", "fr": "Accessibilité"],
        "Granted": ["de": "Erlaubt", "es": "Concedido", "fr": "Autorisé"],
        "Grant": ["de": "Erlauben", "es": "Conceder", "fr": "Autoriser"],
        "Open Privacy Settings": ["de": "Datenschutzeinstellungen öffnen", "es": "Abrir ajustes de privacidad", "fr": "Ouvrir les réglages de confidentialité"],
        "System Shortcuts Conflict": ["de": "Konflikt mit Systemkurzbefehlen", "es": "Conflicto con atajos del sistema", "fr": "Conflit avec les raccourcis système"],
        "Conflict detected with macOS System Settings": ["de": "Konflikt mit macOS-Systemeinstellungen erkannt", "es": "Conflicto detectado con Ajustes del Sistema de macOS", "fr": "Conflit détecté avec Réglages Système de macOS"],
        "OK": ["de": "OK", "es": "OK", "fr": "OK"],
        "Coarse (12.5%)": ["de": "Grob (12,5 %)", "es": "Grande (12,5 %)", "fr": "Large (12,5 %)"],
        "Normal (6.25%)": ["de": "Normal (6,25 %)", "es": "Normal (6,25 %)", "fr": "Normal (6,25 %)"],
        "Fine (3.13%)": ["de": "Fein (3,13 %)", "es": "Fino (3,13 %)", "fr": "Fin (3,13 %)"],
        "Extra-Fine (1.56%)": ["de": "Sehr fein (1,56 %)", "es": "Muy fino (1,56 %)", "fr": "Très fin (1,56 %)"],
        "Compact": ["de": "Kompakt", "es": "Compacto", "fr": "Compact"],
        "Comfortable": ["de": "Komfortabel", "es": "Cómodo", "fr": "Confortable"],
        "Spacious": ["de": "Geräumig", "es": "Espacioso", "fr": "Spacieux"],
        "On": ["de": "Ein", "es": "Activado", "fr": "Activé"],
        "Off": ["de": "Aus", "es": "Desactivado", "fr": "Désactivé"],
        "Connection timed out": ["de": "Zeitüberschreitung der Verbindung", "es": "La conexión agotó el tiempo", "fr": "La connexion a expiré"],
        "Could not read profile — check file format": ["de": "Profil konnte nicht gelesen werden — Dateiformat prüfen", "es": "No se pudo leer el perfil — comprueba el formato", "fr": "Impossible de lire le profil — vérifiez le format"],
        "Failed to load %@": ["de": "%@ konnte nicht geladen werden", "es": "No se pudo cargar %@", "fr": "Échec du chargement de %@"],
        "Couldn't change sample rate. The device refused.": ["de": "Abtastrate konnte nicht geändert werden. Das Gerät hat abgelehnt.", "es": "No se pudo cambiar la frecuencia de muestreo. El dispositivo la rechazó.", "fr": "Impossible de changer la fréquence d’échantillonnage. L’appareil a refusé."],
        "Collapse device details": ["de": "Gerätedetails einklappen", "es": "Contraer detalles del dispositivo", "fr": "Réduire les détails de l’appareil"],
        "Expand device details": ["de": "Gerätedetails ausklappen", "es": "Expandir detalles del dispositivo", "fr": "Développer les détails de l’appareil"],
        "Cannot hide the default device": ["de": "Das Standardgerät kann nicht ausgeblendet werden", "es": "No se puede ocultar el dispositivo predeterminado", "fr": "Impossible de masquer l’appareil par défaut"],
        "Show in main view": ["de": "In Hauptansicht anzeigen", "es": "Mostrar en la vista principal", "fr": "Afficher dans la vue principale"],
        "Hide from main view": ["de": "Aus Hauptansicht ausblenden", "es": "Ocultar de la vista principal", "fr": "Masquer de la vue principale"],
        "Device inspector": ["de": "Geräteinspektor", "es": "Inspector del dispositivo", "fr": "Inspecteur d’appareil"],
        "Unknown device": ["de": "Unbekanntes Gerät", "es": "Dispositivo desconocido", "fr": "Appareil inconnu"],
        "Volume %d percent": ["de": "Lautstärke %d Prozent", "es": "Volumen %d por ciento", "fr": "Volume %d pour cent"],
        "%@, muted": ["de": "%@, stumm", "es": "%@, silenciado", "fr": "%@, muet"],
        "%@, unmuted": ["de": "%@, nicht stumm", "es": "%@, sonido activado", "fr": "%@, son réactivé"],
        "%@, muted, volume at %d percent": ["de": "%@, stumm, Lautstärke bei %d Prozent", "es": "%@, silenciado, volumen al %d por ciento", "fr": "%@, muet, volume à %d pour cent"],
        "%@, volume %d percent": ["de": "%@, Lautstärke %d Prozent", "es": "%@, volumen %d por ciento", "fr": "%@, volume %d pour cent"],
        "%@, not controlled by SoundTune": ["de": "%@, nicht von SoundTune gesteuert", "es": "%@, SoundTune no lo controla", "fr": "%@, non contrôlé par SoundTune"],
        "Not controlled by SoundTune": ["de": "Nicht von SoundTune gesteuert", "es": "SoundTune no lo controla", "fr": "Non contrôlé par SoundTune"]
    ]
    
    init() {
        let table: [String: [String: String]] = [
            "Launch at Login": ["en": "Launch at Login", "tr": "Başlangıçta Çalıştır"],
            "Start SoundTune when you log in": ["en": "Start SoundTune when you log in", "tr": "Giriş yaptığınızda SoundTune'u başlatır"],
            "Theme": ["en": "Theme", "tr": "Tema"],
            "Match macOS, or lock to Light or Dark": ["en": "Match macOS, or lock to Light or Dark", "tr": "macOS görünümüne uydurun veya Açık/Koyu moduna kilitleyin"],
            "Volume": ["en": "Volume", "tr": "Ses Seviyesi"],
            "Default Volume": ["en": "Default Volume", "tr": "Varsayılan Ses"],
            "Initial volume for new apps": ["en": "Initial volume for new apps", "tr": "Yeni uygulamalar için başlangıç sesi"],
            "Loudness Compensation": ["en": "Loudness Compensation", "tr": "Ses Gürlüğü Dengeleme"],
            "Boost low frequencies at low volume": ["en": "Boost low frequencies at low volume", "tr": "Düşük seste bas frekanslarını artırır"],
            "Devices": ["en": "Devices", "tr": "Cihazlar"],
            "Lock Input Device": ["en": "Lock Input Device", "tr": "Giriş Aygıtını Kilitle"],
            "Prevent auto-switching when devices connect": ["en": "Prevent auto-switching when devices connect", "tr": "Yeni aygıtlar bağlandığında otomatik geçişi önler"],
            "System Sounds": ["en": "System Sounds", "tr": "Sistem Sesleri"],
            "Where alerts and effects play": ["en": "Where alerts and effects play", "tr": "Uyarı ve efektlerin çalınacağı yer"],
            "Alert Volume": ["en": "Alert Volume", "tr": "Uyarı Sesi Seviyesi"],
            "Volume for alerts and notifications": ["en": "Volume for alerts and notifications", "tr": "Uyarı ve bildirimler için ses seviyesi"],
            "Language": ["en": "Language", "tr": "Dil"],
            "App Language": ["en": "App Language", "tr": "Uygulama Dili"],
            "Select English or Turkish": ["en": "Select English or Turkish", "tr": "İngilizce veya Türkçe seçin"],
            "Follow macOS or choose a language": ["en": "Follow macOS or choose a language", "tr": "macOS dilini takip edin veya bir dil seçin"],
            "Quit": ["en": "Quit", "tr": "Çıkış Yap"],
            "Quit SoundTune": ["en": "Quit SoundTune", "tr": "SoundTune'dan Çık"],
            "Quit SoundTune (⌘Q)": ["en": "Quit SoundTune (⌘Q)", "tr": "SoundTune'dan Çık (⌘Q)"],
            "Output Devices": ["en": "Output Devices", "tr": "Çıkış Aygıtları"],
            "Input Devices": ["en": "Input Devices", "tr": "Giriş Aygıtları"],
            "Apps": ["en": "Apps", "tr": "Uygulamalar"],
            "Bluetooth": ["en": "Bluetooth", "tr": "Bluetooth"],
            "No apps playing audio": ["en": "No apps playing audio", "tr": "Ses çalan uygulama yok"],
            "ignored · edit to manage": ["en": "ignored · edit to manage", "tr": "yok sayıldı · yönetmek için düzenle"],
            "ignored": ["en": "ignored", "tr": "yok sayıldı"],
            "Ignored": ["en": "Ignored", "tr": "Yok Sayılan"],
            "Turn on Bluetooth to connect devices": ["en": "Turn on Bluetooth to connect devices", "tr": "Cihazları bağlamak için Bluetooth'u açın"],
            "Paired": ["en": "Paired", "tr": "Eşleşen"],
            "Connecting...": ["en": "Connecting...", "tr": "Bağlanıyor..."],
            "Disconnecting...": ["en": "Disconnecting...", "tr": "Bağlantı kesiliyor..."],
            "Connected": ["en": "Connected", "tr": "Bağlı"],
            "Bluetooth is off": ["en": "Bluetooth is off", "tr": "Bluetooth Kapalı"],
            "AirPods Settings": ["en": "AirPods Settings", "tr": "AirPods Ayarları"],
            "Not Available": ["en": "Not Available", "tr": "Kullanılamıyor"],
            "Open AirPods Settings": ["en": "Open AirPods Settings", "tr": "AirPods Ayarlarını Aç"],
            "Open Headphone Settings": ["en": "Open Headphone Settings", "tr": "Kulaklık Ayarlarını Aç"],
            "Settings": ["en": "Settings", "tr": "Ayarlar"],
            "Done reordering": ["en": "Done reordering", "tr": "Sıralama Tamam"],
            "Reorder devices": ["en": "Reorder devices", "tr": "Cihazları Sırala"],
            "Drag or type a number to set priority": ["en": "Drag or type a number to set priority", "tr": "Öncelik belirlemek için sürükleyin veya numara yazın"],
            "No Output": ["en": "No Output", "tr": "Çıkış Yok"],
            "No Input": ["en": "No Input", "tr": "Giriş Yok"],
            "Audio capture access required": ["en": "Audio capture access required", "tr": "Ses yakalama izni gerekiyor"],
            "Enable in System Settings ➔ Privacy & Security ➔ Screen & System Audio Recording": ["en": "Enable in System Settings ➔ Privacy & Security ➔ Screen & System Audio Recording", "tr": "Sistem Ayarları ➔ Gizlilik ve Güvenlik ➔ Ekran ve Sistem Ses Kaydı bölümünden etkinleştirin"],
            "Open System Settings": ["en": "Open System Settings", "tr": "Sistem Ayarlarını Aç"],
            "Grant Access": ["en": "Grant Access", "tr": "İzin Ver"],
            "Use SoundTune's software volume": ["en": "Use SoundTune's software volume", "tr": "SoundTune'un yazılımsal sesini kullan"],
            "Turn on only if the volume slider doesn't work. SoundTune remembers this for each device.": ["en": "Turn on only if the volume slider doesn't work. SoundTune remembers this for each device.", "tr": "Yalnızca ses sürgüsü çalışmıyorsa açın. SoundTune bunu her cihaz için hatırlar."],
            "Transport": ["en": "Transport", "tr": "Bağlantı Türü"],
            "Sample rate": ["en": "Sample rate", "tr": "Örnekleme Hızı"],
            "Format": ["en": "Format", "tr": "Biçim"],
            "Device ID": ["en": "Device ID", "tr": "Cihaz Kimliği"],
            "Copy device ID": ["en": "Copy device ID", "tr": "Cihaz kimliğini kopyala"],
            "Copied": ["en": "Copied", "tr": "Kopyalandı"],
            "Device ID copied": ["en": "Device ID copied", "tr": "Cihaz kimliği kopyalandı"],
            "General": ["en": "General", "tr": "Genel"],
            "Muted": ["en": "Muted", "tr": "Sessiz"],
            "General Settings": ["en": "General Settings", "tr": "Genel Ayarlar"],
            "SoundTune Settings": ["en": "SoundTune Settings", "tr": "SoundTune Ayarları"],
            "System": ["en": "System", "tr": "Sistem"],
            "Light": ["en": "Light", "tr": "Açık"],
            "Dark": ["en": "Dark", "tr": "Koyu"],
            "Auto: ": ["en": "Auto: ", "tr": "Otomatik: "],
            "Hardware": ["en": "Hardware", "tr": "Donanımsal"],
            "DDC": ["en": "DDC", "tr": "DDC"],
            "Software": ["en": "Software", "tr": "Yazılımsal"],
            "Bluetooth is Off": ["en": "Bluetooth is Off", "tr": "Bluetooth Kapalı"],
            "Bluetooth Off": ["en": "Bluetooth Off", "tr": "Bluetooth Kapalı"],
            "Bluetooth is On": ["en": "Bluetooth is On", "tr": "Bluetooth Açık"],
            "Bluetooth On": ["en": "Bluetooth On", "tr": "Bluetooth Açık"],
            "Follow system default": ["en": "Follow system default", "tr": "Sistem varsayılanını takip et"],
            "Follows default": ["en": "Follows default", "tr": "Varsayılanı takip eder"],
            "Follows System Default": ["en": "Follows System Default", "tr": "Sistem Varsayılanını Takip Eder"],
            "Use system default": ["en": "Use system default", "tr": "Sistem varsayılanını kullan"],
            "Select output...": ["en": "Select output...", "tr": "Çıkış seç..."],
            "Pin to menu": ["en": "Pin to menu", "tr": "Menüye sabitle"],
            "Hide app": ["en": "Hide app", "tr": "Uygulamayı gizle"],
            "Reset all settings?": ["en": "Reset all settings?", "tr": "Tüm ayarlar sıfırlansın mı?"],
            "Reset": ["en": "Reset", "tr": "Sıfırla"],
            "Cancel": ["en": "Cancel", "tr": "İptal"],
            "This cannot be undone.": ["en": "This cannot be undone.", "tr": "Bu işlem geri alınamaz."],
            "Equalizer": ["en": "Equalizer", "tr": "Ekolayzer"],
            "Device EQ": ["en": "Device EQ", "tr": "Cihaz EQ"],
            "Bypass": ["en": "Bypass", "tr": "Devre Dışı"],
            "Preamp": ["en": "Preamp", "tr": "Ön Yükseltici"],
            "Import parametric EQ...": ["en": "Import parametric EQ...", "tr": "Parametrik EQ içe aktar..."],
            "Reset EQ": ["en": "Reset EQ", "tr": "EQ Sıfırla"],
            "Preset": ["en": "Preset", "tr": "Hazır Ayar"],
            "Save preset...": ["en": "Save preset...", "tr": "Hazır ayarı kaydet..."],
            "Flat": ["en": "Flat", "tr": "Düz"],
            "Default": ["en": "Default", "tr": "Varsayılan"],
            "Active Device": ["en": "Active Device", "tr": "Aktif Cihaz"],
            "Waveform": ["en": "Waveform", "tr": "Dalga Formu"],
            "Speaker": ["en": "Speaker", "tr": "Hoparlör"],
            "No devices found": ["en": "No devices found", "tr": "Cihaz bulunamadı"],
            "Custom Preset": ["en": "Custom Preset", "tr": "Özel Hazır Ayar"],
            "Delete preset": ["en": "Delete preset", "tr": "Hazır ayarı sil"],
            "Save Preset": ["en": "Save Preset", "tr": "Hazır Ayarı Kaydet"],
            "Preset Name": ["en": "Preset Name", "tr": "Hazır Ayar Adı"],
            "Save": ["en": "Save", "tr": "Kaydet"],
            "AutoEQ Profile": ["en": "AutoEQ Profile", "tr": "AutoEQ Profili"],
            "Select a profile...": ["en": "Select a profile...", "tr": "Bir profil seçin..."],
            "Search headphone models...": ["en": "Search headphone models...", "tr": "Kulaklık modellerini ara..."],
            "Device Priority": ["en": "Device Priority", "tr": "Cihaz Önceliği"],
            "Volume Boost": ["en": "Volume Boost", "tr": "Ses Artışı"],
            "None": ["en": "None", "tr": "Yok"],
            "Default Audio Outputs": ["en": "Default Audio Outputs", "tr": "Varsayılan Ses Çıkışları"],
            "Default Audio Inputs": ["en": "Default Audio Inputs", "tr": "Varsayılan Ses Girişleri"],
            "Device order updated": ["en": "Device order updated", "tr": "Cihaz sırası güncellendi"],
            "Search autoEQ profiles...": ["en": "Search autoEQ profiles...", "tr": "AutoEQ profillerini ara..."],
            "AutoEQ Enabled": ["en": "AutoEQ Enabled", "tr": "AutoEQ Etkin"],
            "AutoEQ Preamp": ["en": "AutoEQ Preamp", "tr": "AutoEQ Ön Yükseltici"],
            "Add to Favorites": ["en": "Add to Favorites", "tr": "Favorilere Ekle"],
            "Remove from Favorites": ["en": "Remove from Favorites", "tr": "Favorilerden Kaldır"],
            "Custom profiles": ["en": "Custom profiles", "tr": "Özel profiller"],
            "Search headphones...": ["en": "Search headphones...", "tr": "Kulaklıkları ara..."],
            "Import AutoEQ Profile": ["en": "Import AutoEQ Profile", "tr": "AutoEQ Profili İçe Aktar"],
            "Favorites": ["en": "Favorites", "tr": "Favoriler"],
            "Catalog": ["en": "Catalog", "tr": "Katalog"],
            "Close": ["en": "Close", "tr": "Kapat"],
            "EQ": ["en": "EQ", "tr": "EQ"],
            "Custom": ["en": "Custom", "tr": "Özel"],
            "off": ["en": "off", "tr": "kapalı"],
            "Open %@": ["en": "Open %@", "tr": "%@ uygulamasını aç"],
            "Close Equalizer": ["en": "Close Equalizer", "tr": "Ekolayzerı Kapat"],
            "Connect": ["en": "Connect", "tr": "Bağlan"],
            "Pin app": ["en": "Pin app", "tr": "Uygulamayı Sabitle"],
            "Unpin app": ["en": "Unpin app", "tr": "Sabitlemeyi Kaldır"],
            "Ignore app": ["en": "Ignore app", "tr": "Uygulamayı Yoksay"],
            "Stop ignoring": ["en": "Stop ignoring", "tr": "Yoksaymayı Durdur"],
            "Imported": ["en": "Imported", "tr": "İçe Aktarılan"],
            "No correction active": ["en": "No correction active", "tr": "Aktif düzeltme yok"],
            "Search or pick a favorite below": ["en": "Search or pick a favorite below", "tr": "Aşağıdan arayın veya favorinizi seçin"],
            "Loading profile...": ["en": "Loading profile...", "tr": "Profil yükleniyor..."],
            "Correction": ["en": "Correction", "tr": "Düzeltme"],
            "Clear search": ["en": "Clear search", "tr": "Aramayı Temizle"],
            "Loading headphone catalog...": ["en": "Loading headphone catalog...", "tr": "Kulaklık kataloğu yükleniyor..."],
            "Type to search headphones": ["en": "Type to search headphones", "tr": "Kulaklıkları aramak için yazın"],
            "No profiles found": ["en": "No profiles found", "tr": "Profil bulunamadı"],
            "Import ParametricEQ.txt...": ["en": "Import ParametricEQ.txt...", "tr": "ParametrikEQ.txt içe aktar..."],
            "Showing %d of %d results": ["en": "Showing %d of %d results", "tr": "%d / %d sonuç gösteriliyor"],
            "%d results": ["en": "%d results", "tr": "%d sonuç"],
            "Single": ["en": "Single", "tr": "Tek"],
            "Multi": ["en": "Multi", "tr": "Çoklu"],
            "Multi · %d devices": ["en": "Multi · %d devices", "tr": "Çoklu · %d aygıt"],
            "Select": ["en": "Select", "tr": "Seç"],
            "Utility": ["en": "Utility", "tr": "Araçlar"],
            "Speech": ["en": "Speech", "tr": "Konuşma"],
            "Listening": ["en": "Listening", "tr": "Dinleme"],
            "Music": ["en": "Music", "tr": "Müzik"],
            "Media": ["en": "Media", "tr": "Medya"],
            "My Presets": ["en": "My Presets", "tr": "Hazır Ayarlarım"],
            "Bass Boost": ["en": "Bass Boost", "tr": "Bas Güçlendirme"],
            "Bass Cut": ["en": "Bass Cut", "tr": "Bas Azaltma"],
            "Treble Boost": ["en": "Treble Boost", "tr": "Tiz Güçlendirme"],
            "Vocal Clarity": ["en": "Vocal Clarity", "tr": "Vokal Netliği"],
            "Podcast": ["en": "Podcast", "tr": "Podcast"],
            "Spoken Word": ["en": "Spoken Word", "tr": "Konuşma"],
            "Loudness": ["en": "Loudness", "tr": "Gürlük"],
            "Late Night": ["en": "Late Night", "tr": "Gece Yarısı"],
            "Small Speakers": ["en": "Small Speakers", "tr": "Küçük Hoparlörler"],
            "Rock": ["en": "Rock", "tr": "Rock"],
            "Pop": ["en": "Pop", "tr": "Pop"],
            "Electronic": ["en": "Electronic", "tr": "Elektronik"],
            "Jazz": ["en": "Jazz", "tr": "Caz"],
            "Classical": ["en": "Classical", "tr": "Klasik"],
            "Hip-Hop": ["en": "Hip-Hop", "tr": "Hip-Hop"],
            "R&B": ["en": "R&B", "tr": "R&B"],
            "Deep": ["en": "Deep", "tr": "Derin"],
            "Acoustic": ["en": "Acoustic", "tr": "Akustik"],
            "Movie": ["en": "Movie", "tr": "Film"],
            "Save current EQ as preset": ["en": "Save current EQ as preset", "tr": "Mevcut EQ'yu hazır ayar olarak kaydet"],
            "Save current EQ curve as a new preset": ["en": "Save current EQ curve as a new preset", "tr": "Mevcut EQ eğrisini yeni hazır ayar olarak kaydet"],
            "Preset name": ["en": "Preset name", "tr": "Hazır ayar adı"],
            "Save preset": ["en": "Save preset", "tr": "Hazır ayarı kaydet"],
            "Confirm save preset": ["en": "Confirm save preset", "tr": "Hazır ayarı kaydetmeyi onayla"],
            "Cancel saving preset": ["en": "Cancel saving preset", "tr": "Hazır ayarı kaydetmeyi iptal et"],
            "Rename preset": ["en": "Rename preset", "tr": "Yeniden Adlandır"],
            "Rename current preset": ["en": "Rename current preset", "tr": "Mevcut hazır ayarı yeniden adlandır"],
            "Confirm rename": ["en": "Confirm rename", "tr": "Yeniden adlandırmayı onayla"],
            "Confirm rename preset": ["en": "Confirm rename preset", "tr": "Hazır ayarı yeniden adlandırmayı onayla"],
            "Cancel renaming preset": ["en": "Cancel renaming preset", "tr": "Hazır ayarı yeniden adlandırmayı iptal et"],
            "Unmute": ["en": "Unmute", "tr": "Sesi Aç"],
            "Mute": ["en": "Mute", "tr": "Sessize Al"],
            "Unmute microphone": ["en": "Unmute microphone", "tr": "Mikrofon Sesini Aç"],
            "Mute microphone": ["en": "Mute microphone", "tr": "Mikrofonu Sessize Al"],
            "Check Now": ["en": "Check Now", "tr": "Şimdi Kontrol Et"],
            "Media keys offline. Retry to reinstall the event tap.": ["en": "Media keys offline. Retry to reinstall the event tap.", "tr": "Medya tuşları çevrimdışı. Olay dinleyicisini yeniden yüklemek için Yeniden Dene'ye basın."],
            "Auto-detected volume control: %@": ["en": "Auto-detected volume control: %@", "tr": "Otomatik algılanan ses kontrolü: %@"],
            "Edit priority position": ["en": "Edit priority position", "tr": "Öncelik konumunu düzenle"],
            "Sample rate: %@. Activate to change.": ["en": "Sample rate: %@. Activate to change.", "tr": "Örnekleme hızı: %@. Değiştirmek için etkinleştirin."],
            "Delete preset %@": ["en": "Delete preset %@", "tr": "%@ hazır ayarını sil"],
            "Volume boost: %@": ["en": "Volume boost: %@", "tr": "Ses artışı: %@"],
            "Volume boost %@": ["en": "Volume boost %@", "tr": "Ses artışı %@"],
            "Edit volume percentage": ["en": "Edit volume percentage", "tr": "Ses yüzdesini düzenle"],
            "No correction active. Search or pick a favorite below.": ["en": "No correction active. Search or pick a favorite below.", "tr": "Aktif düzeltme yok. Aşağıdan arayın veya favorinizi seçin."],
            "Remove correction profile": ["en": "Remove correction profile", "tr": "Düzeltme profilini kaldır"],
            "%@ correction profile": ["en": "%@ correction profile", "tr": "%@ düzeltme profili"],
            "Search headphones": ["en": "Search headphones", "tr": "Kulaklıkları ara"],
            "Import custom profile": ["en": "Import custom profile", "tr": "Özel profili içe aktar"],
            "Enable Chrome ▸ View ▸ Developer ▸ Allow JavaScript from Apple Events": ["en": "Enable Chrome ▸ View ▸ Developer ▸ Allow JavaScript from Apple Events", "tr": "Chrome ▸ Görüntü ▸ Geliştirici ▸ Apple Etkinliklerinden JavaScript'e İzin Ver"],
            "Browser media access required": ["en": "Browser media access required", "tr": "Tarayıcı medya erişimi gerekiyor"],
            "Allow SoundTune to control your browser in System Settings ➔ Privacy & Security ➔ Automation": ["en": "Allow SoundTune to control your browser in System Settings ➔ Privacy & Security ➔ Automation", "tr": "Sistem Ayarları ➔ Gizlilik ve Güvenlik ➔ Otomasyon bölümünden SoundTune'un tarayıcıyı kontrol etmesine izin verin"],
            "SoundTune could not read browser media. Reopen the browser tab and try again.": ["en": "SoundTune could not read browser media. Reopen the browser tab and try again.", "tr": "SoundTune tarayıcı medyasını okuyamadı. Tarayıcı sekmesini yeniden açıp tekrar deneyin."],
            "Volume Step": ["en": "Volume Step", "tr": "Ses Adımı"],
            "How much each keypress changes the volume": ["en": "How much each keypress changes the volume", "tr": "Her tuş basışının sesi ne kadar değiştireceği"],
            "Media Keys": ["en": "Media Keys", "tr": "Medya Tuşları"],
            "Media Keys Control": ["en": "Media Keys Control", "tr": "Medya Tuşları Kontrolü"],
            "Use F11/F12 (or volume keys) to control SoundTune": ["en": "Use F11/F12 (or volume keys) to control SoundTune", "tr": "SoundTune'u kontrol etmek için F11/F12 (veya ses tuşları) kullanın"],
            "HUD Style": ["en": "HUD Style", "tr": "HUD Stili"],
            "How the volume indicator appears": ["en": "How the volume indicator appears", "tr": "Ses göstergesinin nasıl görüneceği"],
            "Hotkeys": ["en": "Hotkeys", "tr": "Kısayol Tuşları"],
            "Show or hide the menu bar popup": ["en": "Show or hide the menu bar popup", "tr": "Menü çubuğu açılır penceresini göster veya gizle"],
            "Raise volume for the app playing audio": ["en": "Raise volume for the app playing audio", "tr": "Ses çalan uygulamanın sesini artır"],
            "Lower volume for the app playing audio": ["en": "Lower volume for the app playing audio", "tr": "Ses çalan uygulamanın sesini azalt"],
            "Mute or unmute the app playing audio": ["en": "Mute or unmute the app playing audio", "tr": "Ses çalan uygulamayı sessize al veya sesi aç"],
            "Welcome to SoundTune": ["en": "Welcome to SoundTune", "tr": "SoundTune'a Hoş Geldiniz"],
            "Next": ["en": "Next", "tr": "İleri"],
            "Get Started": ["en": "Get Started", "tr": "Başla"],
            "Per-App Volume Control": ["en": "Per-App Volume Control", "tr": "Uygulama Başına Ses Kontrolü"],
            "Set different volume levels for each app independently.": ["en": "Set different volume levels for each app independently.", "tr": "Her uygulama için bağımsız olarak farklı ses düzeyleri belirleyin."],
            "Equalizer & Presets": ["en": "Equalizer & Presets", "tr": "Ekolayzer ve Hazır Ayarlar"],
            "Fine-tune audio with per-app and per-device EQ presets.": ["en": "Fine-tune audio with per-app and per-device EQ presets.", "tr": "Uygulama ve cihaz bazlı EQ hazır ayarlarıyla sesi ince ayarlayın."],
            "Equalizer & AutoEQ": ["en": "Equalizer & AutoEQ", "tr": "Ekolayzer ve AutoEQ"],
            "Fine-tune audio with per-app EQ and thousands of headphone correction profiles.": ["en": "Fine-tune audio with per-app EQ and thousands of headphone correction profiles.", "tr": "Uygulama başına EQ ve binlerce kulaklık düzeltme profiliyle sesi ince ayar yapın."],
            "Media Key Control": ["en": "Media Key Control", "tr": "Medya Tuşu Kontrolü"],
            "Take over F10/F11/F12 to control the volume of any app.": ["en": "Take over F10/F11/F12 to control the volume of any app.", "tr": "Herhangi bir uygulamanın sesini kontrol etmek için F10/F11/F12 tuşlarını kullanın."],
            "Why Screen & System Audio Recording?": ["en": "Why Screen & System Audio Recording?", "tr": "Neden Ekran ve Sistem Ses Kaydı?"],
            "SoundTune uses a CoreAudio feature called CATap to read the audio stream of each app — not to record it, just to route and adjust volume independently.": ["en": "SoundTune uses a CoreAudio feature called CATap to read the audio stream of each app — not to record it, just to route and adjust volume independently.", "tr": "SoundTune, her uygulamanın ses akışını okumak için CATap adlı bir CoreAudio özelliği kullanır — kayıt etmek için değil, yalnızca bağımsız olarak yönlendirmek ve sesi ayarlamak için."],
            "No audio data is stored or transmitted. This is how macOS exposes per-app audio to third-party apps.": ["en": "No audio data is stored or transmitted. This is how macOS exposes per-app audio to third-party apps.", "tr": "Hiçbir ses verisi depolanmaz veya iletilmez. macOS'un uygulama başına sesi üçüncü taraf uygulamalara sunma yöntemi budur."],
            "Required Permissions": ["en": "Required Permissions", "tr": "Gerekli İzinler"],
            "Screen & System Audio Recording": ["en": "Screen & System Audio Recording", "tr": "Ekran ve Sistem Ses Kaydı"],
            "Needed to intercept per-app audio streams via CATap.": ["en": "Needed to intercept per-app audio streams via CATap.", "tr": "CATap aracılığıyla uygulama başına ses akışlarını yakalamak için gereklidir."],
            "Accessibility": ["en": "Accessibility", "tr": "Erişilebilirlik"],
            "Needed for media key interception (F10/F11/F12).": ["en": "Needed for media key interception (F10/F11/F12).", "tr": "Medya tuşu yakalama (F10/F11/F12) için gereklidir."],
            "Needed to connect and manage Bluetooth audio devices.": ["en": "Needed to connect and manage Bluetooth audio devices.", "tr": "Bluetooth ses cihazlarını bağlamak ve yönetmek için gereklidir."],
            "Bluetooth access required": ["en": "Bluetooth access required", "tr": "Bluetooth erişimi gerekli"],
            "Needed to discover and connect paired Bluetooth audio devices.": ["en": "Needed to discover and connect paired Bluetooth audio devices.", "tr": "Eşleştirilmiş Bluetooth ses cihazlarını bulmak ve bağlamak için gereklidir."],
            "System Audio": ["en": "System Audio", "tr": "Sistem Sesi"],
            "Follows macOS default": ["en": "Follows macOS default", "tr": "macOS varsayılanını takip eder"],
            "Not available in multi mode": ["en": "Not available in multi mode", "tr": "Çoklu çıkış modunda kullanılamaz"],
            "devices": ["en": "devices", "tr": "cihaz"],
            "Toggle SoundTune Popup": ["en": "Toggle SoundTune Popup", "tr": "Pencereyi Göster/Gizle"],
            "Open Settings": ["en": "Open Settings", "tr": "Ayarları Aç"],
            "App Volume Up": ["en": "App Volume Up", "tr": "Uygulama Sesini Artır"],
            "App Volume Down": ["en": "App Volume Down", "tr": "Uygulama Sesini Azalt"],
            "App Mute": ["en": "App Mute", "tr": "Uygulamayı Sessize Al"],
            "Open settings view": ["en": "Open settings view", "tr": "Ayarlar görünümünü aç"],
            "Granted": ["en": "Granted", "tr": "Verildi"],
            "Grant": ["en": "Grant", "tr": "İzin Ver"],
            "Access granted — volume keys now control SoundTune.": ["en": "Access granted — volume keys now control SoundTune.", "tr": "Erişim sağlandı — ses tuşları artık SoundTune'u kontrol ediyor."],
            "SoundTune needs Accessibility to intercept F10 / F11 / F12.": ["en": "SoundTune needs Accessibility to intercept F10 / F11 / F12.", "tr": "SoundTune'un F10 / F11 / F12 tuşlarını yakalamak için Erişilebilirlik iznine ihtiyacı var."],
            "Open Privacy Settings": ["en": "Open Privacy Settings", "tr": "Gizlilik Ayarlarını Aç"],
            "Add to multi-output": ["en": "Add to multi-output", "tr": "Çoklu çıkışa ekle"],
            "Remove from multi-output": ["en": "Remove from multi-output", "tr": "Çoklu çıkıştan çıkar"],
            "Settings...": ["en": "Settings...", "tr": "Ayarlar..."],
            "Show Desktop": ["en": "Show Desktop", "tr": "Masaüstünü Göster"],
            "Mission Control": ["en": "Mission Control", "tr": "Mission Control"],
            "Application Windows": ["en": "Application Windows", "tr": "Uygulama Pencereleri"],
            "Show Dashboard": ["en": "Show Dashboard", "tr": "Dashboard'u Göster"],
            "System Shortcuts Conflict": ["en": "System Shortcuts Conflict", "tr": "Sistem Kısayolu Çakışması"],
            "macOS system shortcuts take priority over SoundTune. If a shortcut (like F11 or F12) is not working, disable or change it in System Settings.": ["en": "macOS system shortcuts take priority over SoundTune. If a shortcut (like F11 or F12) is not working, disable or change it in System Settings.", "tr": "macOS sistem kısayolları SoundTune'dan önceliklidir. Eğer bir kısayol (F11 veya F12 gibi) çalışmıyorsa, Sistem Ayarları'ndan devre dışı bırakın veya değiştirin."],
            "Open Keyboard Shortcuts Settings": ["en": "Open Keyboard Shortcuts Settings", "tr": "Sistem Kısayol Ayarlarını Aç"],
            "Currently assigned to %@ in macOS System Settings.": ["en": "Currently assigned to %@ in macOS System Settings.", "tr": "Şu anda macOS Sistem Ayarlarında %@ tuşuna atanmış durumda."],
            "Conflict detected with macOS System Settings": ["en": "Conflict detected with macOS System Settings", "tr": "macOS Sistem Ayarları ile çakışma algılandı"],
            "Restricted Shortcut": ["en": "Restricted Shortcut", "tr": "Kısıtlı Kısayol"],
            "The shortcut %@ is reserved by macOS for standard system functions (such as Save, Quit, or Close) and cannot be assigned in SoundTune. Please choose a different key combination.": ["en": "The shortcut %@ is reserved by macOS for standard system functions (such as Save, Quit, or Close) and cannot be assigned in SoundTune. Please choose a different key combination.", "tr": "Seçtiğiniz %@ kısayolu macOS tarafından standart sistem işlevleri (Kaydet, Çık veya Kapat gibi) için ayrılmıştır ve SoundTune içinde kullanılamaz. Lütfen farklı bir tuş kombinasyonu seçin."],
            "OK": ["en": "OK", "tr": "Tamam"],
            "Audio Device Reconnected": ["en": "Audio Device Reconnected", "tr": "Ses Cihazı Yeniden Bağlandı"],
            "\"%@\" is back. %d app(s) switched back.": ["en": "\"%@\" is back. %d app(s) switched back.", "tr": "\"%@\" geri döndü. %d uygulama tekrar bu cihaza geçti."],
            "Audio Device Disconnected": ["en": "Audio Device Disconnected", "tr": "Ses Cihazı Bağlantısı Kesildi"],
            "\"%@\" disconnected. %d app(s) switched to %@": ["en": "\"%@\" disconnected. %d app(s) switched to %@", "tr": "\"%@\" bağlantısı kesildi. %d uygulama %@ cihazına geçti."],
            "Default Audio Device Changed": ["en": "Default Audio Device Changed", "tr": "Varsayılan Ses Cihazı Değişti"],
            "%d app(s) switched to \"%@\"": ["en": "%d app(s) switched to \"%@\"", "tr": "%d uygulama \"%@\" cihazına geçti."],
            "Select an AutoEQ ParametricEQ.txt file": ["en": "Select an AutoEQ ParametricEQ.txt file", "tr": "Bir AutoEQ ParametricEQ.txt dosyası seçin"],
            "Preview": ["en": "Preview", "tr": "Önizleme"],
            "Hz": ["en": "Hz", "tr": "Hz"],
            "DEFAULT": ["en": "DEFAULT", "tr": "VARSAYILAN"],
            "Coarse (12.5%)": ["en": "Coarse (12.5%)", "tr": "Büyük (%12,5)"],
            "Normal (6.25%)": ["en": "Normal (6.25%)", "tr": "Normal (%6,25)"],
            "Fine (3.13%)": ["en": "Fine (3.13%)", "tr": "İnce (%3,13)"],
            "Extra-Fine (1.56%)": ["en": "Extra-Fine (1.56%)", "tr": "Çok İnce (%1,56)"],
            "Compact": ["en": "Compact", "tr": "Kompakt"],
            "Comfortable": ["en": "Comfortable", "tr": "Rahat"],
            "Spacious": ["en": "Spacious", "tr": "Geniş"],
            "On": ["en": "On", "tr": "Açık"],
            "Off": ["en": "Off", "tr": "Kapalı"],
            "Connection timed out": ["en": "Connection timed out", "tr": "Bağlantı zaman aşımına uğradı"],
            "Could not read profile — check file format": ["en": "Could not read profile — check file format", "tr": "Profil okunamadı — dosya biçimini kontrol edin"],
            "Failed to load %@": ["en": "Failed to load %@", "tr": "%@ yüklenemedi"],
            "Couldn't change sample rate. The device refused.": ["en": "Couldn't change sample rate. The device refused.", "tr": "Örnekleme hızı değiştirilemedi. Cihaz isteği reddetti."],
            "Collapse device details": ["en": "Collapse device details", "tr": "Cihaz ayrıntılarını daralt"],
            "Expand device details": ["en": "Expand device details", "tr": "Cihaz ayrıntılarını genişlet"],
            "Cannot hide the default device": ["en": "Cannot hide the default device", "tr": "Varsayılan cihaz gizlenemez"],
            "Show in main view": ["en": "Show in main view", "tr": "Ana görünümde göster"],
            "Hide from main view": ["en": "Hide from main view", "tr": "Ana görünümden gizle"],
            "Close device inspector": ["en": "Close device inspector", "tr": "Cihaz inceleyicisini kapat"],
            "Open device inspector": ["en": "Open device inspector", "tr": "Cihaz inceleyicisini aç"],
            "Device inspector": ["en": "Device inspector", "tr": "Cihaz inceleyicisi"],
            "Returns to no correction state": ["en": "Returns to no correction state", "tr": "Düzeltmesiz duruma döner"],
            "Opens file picker for ParametricEQ.txt files": ["en": "Opens file picker for ParametricEQ.txt files", "tr": "ParametricEQ.txt dosyaları için dosya seçiciyi açar"],
            "Apply this correction profile": ["en": "Apply this correction profile", "tr": "Bu düzeltme profilini uygula"],
            "Reinstalls the media-key event tap.": ["en": "Reinstalls the media-key event tap.", "tr": "Medya tuşu olay dinleyicisini yeniden yükler."],
            "Shows the macOS Accessibility permission prompt.": ["en": "Shows the macOS Accessibility permission prompt.", "tr": "macOS Erişilebilirlik izin istemini gösterir."],
            "Unknown device": ["en": "Unknown device", "tr": "Bilinmeyen cihaz"],
            "Volume %d percent": ["en": "Volume %d percent", "tr": "Ses seviyesi yüzde %d"],
            "%@, muted": ["en": "%@, muted", "tr": "%@, sessiz"],
            "%@, unmuted": ["en": "%@, unmuted", "tr": "%@, sesi açık"],
            "%@, muted, volume at %d percent": ["en": "%@, muted, volume at %d percent", "tr": "%@, sessiz, ses seviyesi yüzde %d"],
            "%@, volume %d percent": ["en": "%@, volume %d percent", "tr": "%@, ses seviyesi yüzde %d"],
            "%@, not controlled by SoundTune": ["en": "%@, not controlled by SoundTune", "tr": "%@, SoundTune tarafından kontrol edilmiyor"],
            "Not controlled by SoundTune": ["en": "Not controlled by SoundTune", "tr": "SoundTune tarafından kontrol edilmiyor"],
            "Media keys offline": ["en": "Media keys offline", "tr": "Medya tuşları çevrimdışı"],
            "The system disabled SoundTune's event tap — usually after a sleep/wake cycle or a main-thread stall. Retry to reinstall it.": ["en": "The system disabled SoundTune's event tap — usually after a sleep/wake cycle or a main-thread stall. Retry to reinstall it.", "tr": "Sistem SoundTune'un olay dinleyicisini devre dışı bıraktı — genellikle uyku/uyanma döngüsü veya ana iş parçacığı takılması sonrası. Yeniden yüklemek için Yeniden Dene'ye basın."],
            "Retry": ["en": "Retry", "tr": "Yeniden Dene"]
        ]
        self.translations = table
    }
    
    var translationCount: Int { translations.count }

    func translate(_ key: String) -> String {
        let languageCode = currentLanguage.resolvedLanguage.rawValue
        if let translated = translations[key]?[languageCode] ?? supplementalTranslations[key]?[languageCode] {
            return translated
        }
        return translations[key]?[AppLanguage.english.rawValue] ?? key
    }

    func formatPercentage(_ fraction: Double, maximumFractionDigits: Int = 2) -> String {
        let formatter = NumberFormatter()
        formatter.numberStyle = .percent
        formatter.locale = currentLanguage.locale
        formatter.minimumFractionDigits = 0
        formatter.maximumFractionDigits = maximumFractionDigits
        return formatter.string(from: NSNumber(value: fraction)) ?? "\(fraction * 100)%"
    }
}

@MainActor
func t(_ key: String) -> String {
    // Read currentLanguage to register observation dependency
    _ = LanguageManager.shared.currentLanguage
    return LanguageManager.shared.translate(key)
}
